run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: vendor

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gofmt
    - goimports
    - gocyclo
    - golint
    - goconst
    - unconvert
    - unparam
    - ineffassign
    - scopelint