FROM golang:latest AS builder

LABEL maintainer="Videocoin" description="transcoding client streams"

WORKDIR /go/src/github.com/videocoin/transcode

ADD ./ ./

ENV GO111MODULE=off

RUN make build-transinit

FROM phusion/baseimage AS release

COPY --from=builder /go/src/github.com/videocoin/transcode/bin/transinit ./

CMD [ "./transinit" ]
