FROM golang:1.12.4 AS builder

LABEL maintainer="Videocoin" description="transcoding client streams"

WORKDIR /go/src/github.com/videocoin/transcode

ADD ./ ./

RUN make build-transinit

FROM bitnami/minideb:jessie

COPY --from=builder /go/src/github.com/videocoin/transcode/bin/transinit ./

CMD [ "./transinit" ]
